version: '2'

services:
  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/swift:3'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
    volumes:
      - .:/app
